name: Auto Create Draft PR with AI Summary

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  create_pr_with_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get list of changed files compared to main
        id: changes
        run: |
          files=$(git diff origin/main --name-only)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build summary input from changed files
        id: build_summary_input
        run: |
          summary_input=""
          for file in ${{ steps.changes.outputs.files }}; do
            if [ -f "$file" ]; then
              summary_input+="### $file\n"
              summary_input+=$(cat "$file")
              summary_input+="\n\n"
            fi
          done
          echo "summary_input<<EOF" >> $GITHUB_OUTPUT
          echo -e "$summary_input" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call AI summarizer API
        id: ai_summary
        run: |
          # Safely encode JSON with jq
          json_data=$(jq -n --arg diff "${{ steps.build_summary_input.outputs.summary_input }}" '{diff: $diff}')
          response=$(curl -s -X POST https://f225-2401-4900-a1c8-cf81-34ae-d187-ba4f-21a.ngrok-free.app/summarize \
            -H "Content-Type: application/json" \
            -d "$json_data")
          summary=$(echo "$response" | jq -r '.summary')
          echo "summary=$summary" >> $GITHUB_ENV

      - name: Get branch name
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Create draft pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Auto PR: Update with AI summary"
          title: "Auto PR with AI summary"
          body: ${{ env.summary }}
          draft: true
          base: main
          branch: ${{ env.branch_name }}
