name: Auto Create Draft PR with AI Summary

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  create_pr_with_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get list of changed files
        id: changes
        run: |
          echo "files=$(git diff origin/main --name-only | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Build summary input from changed files
        id: build_summary_input
        run: |
          summary_input=""
          for file in ${{ steps.changes.outputs.files }}; do
            if [ -f "$file" ]; then
              summary_input+="### $file\n"
              summary_input+="$(cat "$file")\n\n"
            fi
          done
          # Store it in an output file
          echo "$summary_input" > summary_input.txt
        shell: bash

      - name: Call AI summarizer API
        id: ai_summary
        run: |
          summary_input=$(<summary_input.txt)
          json_data=$(jq -n --arg diff "$summary_input" '{diff: $diff}')
          response=$(curl -s -X POST https://f225-2401-4900-a1c8-cf81-34ae-d187-ba4f-21a.ngrok-free.app/summarize \
            -H "Content-Type: application/json" \
            -d "$json_data")
          summary=$(echo "$response" | jq -r '.summary')
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$summary" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch
        run: echo "name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Create draft pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Auto PR: Update with AI summary"
          title: "Auto PR with AI summary"
          body: ${{ steps.ai_summary.outputs.summary }}
          draft: true
          base: main
          branch: ${{ steps.branch.outputs.name }}
