name: AI PR Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-pr-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate AI PR Summary and update PR description
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          import os
          import requests

          GH_TOKEN = os.environ['GH_TOKEN']
          GROQ_API_KEY = os.environ['GROQ_API_KEY']
          REPO = os.environ['GITHUB_REPOSITORY']
          PR_NUMBER = os.environ['PR_NUMBER']

          # Get PR details
          pr_url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}"
          headers = {
              "Authorization": f"token {GH_TOKEN}",
              "Accept": "application/vnd.github.v3+json"
          }
          pr = requests.get(pr_url, headers=headers).json()

          # Get list of changed files
          files_url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}/files"
          files = requests.get(files_url, headers=headers).json()

          summaries = []
          for file in files:
              filename = file['filename']
              patch = file.get('patch', '')
              if patch:
                  prompt = (
                      f"Summarize the following code changes in '{filename}' for a pull request description. "
                      "Focus only on what has changed in the code, not on metadata, formatting or stylistic details:\n\n"
                      f"{patch}"
                  )
                  groq_response = requests.post(
                      "https://api.groq.com/openai/v1/chat/completions",
                      headers={
                          "Authorization": f"Bearer {GROQ_API_KEY}",
                          "Content-Type": "application/json"
                      },
                      json={
                          "model": "llama3-70b-8192",
                          "messages": [
                              {"role": "system", "content": "You are a helpful assistant that summarizes code changes in pull requests."},
                              {"role": "user", "content": prompt}
                          ],
                          "max_tokens": 256,
                          "temperature": 0.4
                      }
                  )
                  result = groq_response.json()
                  ai_summary = result['choices'][0]['message']['content'].strip()
                  summaries.append(f"**{filename}**\n{ai_summary}")

          summary_text = "\n\n".join(summaries) if summaries else "No code changes detected for AI summary."

          # Update PR description
          patch = {
              "body": f"### AI-generated Summary of Code Changes\n\n{summary_text}\n\n---\n*This summary was generated by Groq Llama3-70B.*"
          }
          requests.patch(pr_url, headers=headers, json=patch)

        shell: python
