name: AI PR Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-pr-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run AI PR Summary script
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python scripts/ai_pr_summary.py  # Update path if script is elsewhere
