name: AI PR Summary

on:
  pull_request:
    types: [opened]

jobs:
  generate_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Verify jq and gh Installation
        run: |
          jq --version
          gh --version

      - name: Run Groq Summary Script
        run: bash .github/scripts/generate-summary.sh
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Update PR description
        run: |
          BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)
          SUMMARY=$(cat summary.txt)
          NEW_BODY="### 🧠 AI-Generated Summary\n\n${SUMMARY}\n\n---\n\n${BODY}"
          gh pr edit ${{ github.event.pull_request.number }} --body "$NEW_BODY"
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
