name: AI PR Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-pr-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Fetch, batch, and summarize all PRs
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/fetch_and_batch_prs.py

      - name: Update PR description with combined summary
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          import os
          import requests

          GH_TOKEN = os.environ['GH_TOKEN']
          PR_NUMBER = os.environ['PR_NUMBER']
          REPO = os.environ['GITHUB_REPOSITORY']

          with open("combined_pr_summary.md", "r") as f:
              summary = f.read()

          pr_url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}"
          headers = {
              "Authorization": f"token {GH_TOKEN}",
              "Accept": "application/vnd.github.v3+json"
          }
          patch = {
              "body": summary
          }
          requests.patch(pr_url, headers=headers, json=patch)

        shell: python
